[ids]
*

[main]
leftmeta = layer(cmd)
rightmeta = layer(cmd)
leftalt = layer(alt)
rightalt = layer(alt)

[cmd:M]
b = C-b
i = C-i
u = C-u
r = C-r
z = C-z
a = C-a
left = home
right = end
up = C-home
down = C-end
shift.left = S-home
shift.right = S-end
shift.up = C-S-home
shift.down = C-S-end
backspace = macro(S-home backspace)

[alt:A]
# option+arrow on macs
left = C-left
right = C-right
shift.left = C-S-left
shift.right = C-S-right

# option+backspace on macs
backspace = C-backspace

# Back/forward navigation
h = A-left
l = A-right
